from actions_toolkit import core
import logging

ENV_VARIABLES = {
    #application env variables
    'APPLICATION_NAME': core.get_input('applicationName', required=True),
    'REPOSITORY': core.get_input('repository', required=True),
    'TLA_NAME': core.get_input('tlaName', required=True),
    'BRAND': core.get_input('brand', required=True),
    'ENVIRONMENT': core.get_input('environment', required=True),

    # Release details env variables
    'RELEASE_NAME': core.get_input('releaseName', required=True),
    'BUILD_NUMBER': core.get_input('buildNumber', required=True),

    # Confluence env variables (not required)
    'CONFLUENCE_USERNAME': core.get_input('confluenceUsername', required=False),
    'CONFLUENCE_URL': core.get_input('confluenceUrl', required=False),
    'CONFLUENCE_PAGE_ID': core.get_input('confluencePageId', required=False),
    'CONFLUENCE_SPACE': core.get_input('confluenceSpace', required=False),
    'CONFLUENCE_API_TOKEN': core.get_input('confluenceApiToken', required=False),

    #hardcoded release notes files name generated by workflow action
    "RELEASE_LOG_FILE_PATH" : './release.txt',

    #for testing purposes
    'CONFLUENCE_EXISTING_PAGE' : core.get_input('confluenceExistingPage', required=False),
    'CONFLUENCE_PAGE_VERSION' : core.get_input('confluencePageVersion', required=False)
}

publish_to_confluence = True

#Setting basic logging config
logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s [%(levelname)s] %(message)s',
                    handlers=[logging.StreamHandler()])

"""
    Validate the values of environment variables.
    If any value is empty or None, raise an error.
    
    Confluence variables are optional, if one of them is not provided, confluence integration will not be executed.
"""
def validate_env_variables():

    for key, value in ENV_VARIABLES.items():
        
        if not value:
            if key.startswith('CONFLUENCE_'):
                # Confluence variables are optional, log a warning if empty
                warning_message = f"Warning: {key} is empty or None. Confluence integration will not execute."
                logging.warning(warning_message)
                publish_to_confluence = False
            else:
                error_message = f"Error: {key} cannot be empty or None."
                logging.error(error_message)
                raise ValueError(error_message)
            
    logging.info('All values are present.')

            
validate_env_variables()