name: "Generate release notes"
description: "Generate release notes for a Github project"

inputs:

  deployEnvironment:
    description: "Environment used ex (qa)"
    required: true

  version:
    description: "Build number convention (ex 1.0.0)"
    required: true

  brand:
    description: "Brand Name (ex bf)"
    required: false

  appVersion:
    description: "The version of the published package used for this release (ex. 1.0.192)"
    required: false

  additionalBodyInfo:
    description: "Additional information to be passed in the release message"
    required: false

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate Release Notes
      id: generate_release_notes
      shell: bash
      run: /bin/bash "${{ github.action_path }}/entry.sh"
      env:
        version: ${{ inputs.version }}
        appVersion: ${{ inputs.appVersion }}
        brand: ${{ inputs.brand }}
        env: ${{ inputs.deployEnvironment }}
        body: ${{ inputs.additionalBodyInfo }}

    - name: Create GitHub release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.generate_release_notes.outputs.new_tag }}
        release_name: ${{ steps.generate_release_notes.outputs.release_name }}
        body: ${{ steps.generate_release_notes.outputs.release_message }}
        prerelease: ${{ inputs.deployEnvironment == 'prd' && 'false' || 'true' }}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      if: steps.generate_release_notes.outputs.new_tag != ''