name: "Generate release notes"
description: "Generate release notes and publish to confluence"

inputs:
  applicationName:
    description: "Application name"
    required: true

  tlaName:
    description: "TLA Name"
    required: true

  brand:
    description: "Brand"
    required: true

  environment:
    description: "Environment"
    required: true

  confluenceUsername:
    description: "Confluence Username"
    required: false

  confluenceUrl:
    description: "Confluence URL"
    required: false

  confluencePageId:
    description: "Confluence Page ID"
    required: false

  confluenceSpace:
    description: "Confluence Space"
    required: false

  confluenceApiToken:
    description: "Confluence API Token"
    required: false

  confluenceExistingPage:
    description: "Confluence Existing Page"
    required: false

  confluencePageVersion:
    description: "Confluence Page Version"
    required: false

  apiToken:
    description: "Token for test"
    required: true

runs:
  using: composite
  steps:

  - name: Checkout
    uses: actions/checkout@v4
    with:
      repository: dragomira2/uki-release-notes-action
      token: ${{ inputs.apiToken }}

  - name: Set up Python
    uses: actions/setup-python@v4
    with:
      python-version: '3.9'

  - name: Install dependencies
    shell: bash
    run: pip install jinja2 requests

  - name: Set Environment Variables
    run: |
        echo "APPLICATION_NAME=${{ inputs.applicationName }}" >> $GITHUB_ENV
        echo "TLA_NAME=${{ inputs.tlaName }}" >> $GITHUB_ENV
        echo "BRAND=${{ inputs.brand }}" >> $GITHUB_ENV
        echo "CONFLUENCE_USERNAME=${{ inputs.confluenceUsername }}" >> $GITHUB_ENV
        echo "CONFLUENCE_URL=${{ inputs.confluenceUrl }}" >> $GITHUB_ENV
        echo "CONFLUENCE_PAGE_ID=${{ inputs.confluencePageId }}" >> $GITHUB_ENV
        echo "CONFLUENCE_SPACE=${{ inputs.confluenceSpace }}" >> $GITHUB_ENV
        echo "CONFLUENCE_API_TOKEN=${{ inputs.confluenceApiToken }}" >> $GITHUB_ENV
        echo "CONFLUENCE_EXISTING_PAGE=${{ inputs.confluenceExistingPage }}" >> $GITHUB_ENV
        echo "CONFLUENCE_PAGE_VERSION=${{ inputs.confluencePageVersion }}" >> $GITHUB_ENV
    shell: bash
  
  - name: Validate inputs
    shell: bash
    run: python scripts/validate_env_variables.py
      
  - name: Run python script
    shell: bash
    run: python scripts/script.py