name: "Generate release notes"
description: "Generate release notes and publish to confluence"

inputs:

  tlaName:
    description: "TLA Name"
    required: true

  environment:
    description: "Environment"
    required: true

  brand:
    description: "Brand Name"
    required: true

  version:
    description: "Build number convention (ex 1.0.0)"
    required: true

  appVersion:
    description: "The version of the published package used for this release (ex. 1.0.192)"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate Release Notes
      id: generate_release
      shell: bash
      run: sh "${{ github.action_path }}/entry.sh"

    - name: Create GitHub release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.generate_release.outputs.new_tag }}
        release_name: ${{ steps.generate_release.outputs.release_name }}
        body: ${{ steps.release_description.outputs.release_message }}
        prerelease: ${{ inputs.environment == 'prd' && 'false' || 'true' }}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}